import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer/Footer'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AW | Alex Warren | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* Layout */}

      {/* Main */}

      {/* About */}

      {/* Skills */}

      {/* Portfolio */}

      {/* Blog */}

      {/* Contact */}
      <main className={styles.main}>
        Hello World
      </main>

    <Footer />
    </div>
  )
}

export default Home
